config/routes.rb
Talkyapp::Application.routes.draw do
  devise_for :users
  root to: 'users#index'

  get '/genres/new', controller: 'genres', action: 'new', as: 'new_genre'
  post '/genres', controller: 'genres', action: 'create', as: 'genres'

  get '/genres', controller: 'genres', action: 'index'
  get '/genres/:id', controller: 'genres', action: 'show', as: 'genre'

  get '/genres/:id/edit', controller: 'genres', action: 'edit', as: 'edit_genre'
  patch '/genres/:id', controller: 'genres', action: 'update'

  delete '/genres/:id', controller: 'genres', action: 'destroy'

  get '/categories/new', controller: 'categories', action: 'new', as: 'new_category'
  post '/categories', controller: 'categories', action: 'create', as: 'categories'

  get '/categories', controller: 'categories', action: 'index'
  get '/categories/:id', controller: 'categories', action: 'show', as: 'category'

  get '/categories/:id/edit', controller: 'categories', action: 'edit', as: 'edit_category'
  patch '/categories/:id', controller: 'categories', action: 'update'

  delete '/categories/:id', controller: 'categories', action: 'destroy'

  get '/followers/new', controller: 'followers', action: 'new', as: 'new_follower'
  post '/followers', controller: 'followers', action: 'create', as: 'followers'

  get '/followers', controller: 'followers', action: 'index'
  get '/followers/:id', controller: 'followers', action: 'show', as: 'follower'

  get '/followers/:id/edit', controller: 'followers', action: 'edit', as: 'edit_follower'
  patch '/followers/:id', controller: 'followers', action: 'update'

  delete '/followers/:id', controller: 'followers', action: 'destroy'

  get '/stories/new', controller: 'stories', action: 'new', as: 'new_story'
  post '/stories', controller: 'stories', action: 'create', as: 'stories'

  get '/stories', controller: 'stories', action: 'index'
  get '/stories/:id', controller: 'stories', action: 'show', as: 'story'

  get '/stories/:id/edit', controller: 'stories', action: 'edit', as: 'edit_story'
  patch '/stories/:id', controller: 'stories', action: 'update'

  delete '/stories/:id', controller: 'stories', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create', as: 'users'

  get '/users', controller: 'users', action: 'index'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  belongs_to :story
  belongs_to :category
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  before_action :go_to_home

  def go_to_home
    redirect_to root_url, :alert => "This page does not exist."
  end

  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find_by(id: params[:id])
  end

  def new
    @stories = Story.all
    @categories = Category.all
  end

  def create
    @genre = Genre.new
    @genre.story_id = params[:story_id]
    @genre.category_id = params[:category_id]

    if @genre.save
      redirect_to genres_url, notice: "Genre created successfully."
    else
      render 'new'
    end
  end

  def edit
    @genre = Genre.find_by(id: params[:id])
  end

  def update
    @genre = Genre.find_by(id: params[:id])
    @genre.story_id = params[:story_id]
    @genre.category_id = params[:category_id]

    if @genre.save
      redirect_to genres_url, notice: "Genre updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @genre = Genre.find_by(id: params[:id])
    @genre.destroy

    redirect_to genres_url, notice: "Genre deleted."
  end
end

app/views/genres/edit.html.erb
<div class="page-header">
  <h1>Editing Genre #<%= @genre.id %></h1>
</div>

<%= form_tag(genre_url(@genre), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :story_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= number_field_tag :story_id, @genre.story_id, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :category_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= number_field_tag :category_id, @genre.category_id, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update Genre", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/genres/index.html.erb
<div class="page-header">
  <h1>Genres</h1>
</div>

<p><%= link_to 'Add a New Genre', new_genre_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Story</th>
      <th>Category</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= genre.story.name %></td>
        <td><%= genre.category.name %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, genre_url(genre), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_genre_url(genre), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, genre_url(genre), method: 'delete', data: { confirm: "Do you really want to delete this genre?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/genres/new.html.erb
<div class="page-header">
  <h1>New Genre</h1>
</div>

<%= form_tag(genres_url, method: 'post', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :story_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :story_id, options_from_collection_for_select(@stories, "id", "name"), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :category_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :category_id, options_from_collection_for_select(@categories, "id", "name"), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Genre", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/genres/show.html.erb
<div class="page-header">
  <h1>Genre #<%= @genre.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt>Story</dt>
  <dd><%= @genre.story_id %></dd>

  <dt>Category</dt>
  <dd><%= @genre.category_id %></dd>

</dl>