config/routes.rb
Talkyapp::Application.routes.draw do
  devise_for :users
  root to: 'users#index'

  get '/genres/new', controller: 'genres', action: 'new', as: 'new_genre'
  post '/genres', controller: 'genres', action: 'create', as: 'genres'

  get '/genres', controller: 'genres', action: 'index'
  get '/genres/:id', controller: 'genres', action: 'show', as: 'genre'

  get '/genres/:id/edit', controller: 'genres', action: 'edit', as: 'edit_genre'
  patch '/genres/:id', controller: 'genres', action: 'update'

  delete '/genres/:id', controller: 'genres', action: 'destroy'

  get '/categories/new', controller: 'categories', action: 'new', as: 'new_category'
  post '/categories', controller: 'categories', action: 'create', as: 'categories'

  get '/categories', controller: 'categories', action: 'index'
  get '/categories/:id', controller: 'categories', action: 'show', as: 'category'

  get '/categories/:id/edit', controller: 'categories', action: 'edit', as: 'edit_category'
  patch '/categories/:id', controller: 'categories', action: 'update'

  delete '/categories/:id', controller: 'categories', action: 'destroy'

  get '/followers/new', controller: 'followers', action: 'new', as: 'new_follower'
  post '/followers', controller: 'followers', action: 'create', as: 'followers'

  get '/followers', controller: 'followers', action: 'index'
  get '/followers/:id', controller: 'followers', action: 'show', as: 'follower'

  get '/followers/:id/edit', controller: 'followers', action: 'edit', as: 'edit_follower'
  patch '/followers/:id', controller: 'followers', action: 'update'

  delete '/followers/:id', controller: 'followers', action: 'destroy'

  get '/stories/new', controller: 'stories', action: 'new', as: 'new_story'
  post '/stories', controller: 'stories', action: 'create', as: 'stories'

  get '/stories', controller: 'stories', action: 'index'
  get '/stories/:id', controller: 'stories', action: 'show', as: 'story'

  get '/stories/:id/edit', controller: 'stories', action: 'edit', as: 'edit_story'
  patch '/stories/:id', controller: 'stories', action: 'update'

  delete '/stories/:id', controller: 'stories', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create', as: 'users'

  get '/users', controller: 'users', action: 'index'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/models/follower.rb
class Follower < ActiveRecord::Base
  belongs_to :following, :class_name => "User", :foreign_key => "user_id"
  belongs_to :followed, :class_name => "User", :foreign_key => "following_id"
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController

  before_action :go_to_home,:only => [:index, :show, :new, :edit, :udpate]

  def go_to_home
    redirect_to root_url, :alert => "This page does not exist."
  end

  def index
    @followers = Follower.all
  end

  def show
    @follower = Follower.find_by(id: params[:id])
  end

  def new
    @users = User.all
  end

  def create
    @follower = Follower.new
    @follower.user_id = current_user.id
    @follower.following_id = params[:fid]
    @follower.favorite = nil

    if @follower.save
      redirect_to users_url, notice: "You are now following #{User.find_by(id: params[:fid]).full_name}"
    else
      render 'new'
    end
  end

  def edit
    @follower = Follower.find_by(id: params[:id])
  end

  def update
    @follower = Follower.find_by(id: params[:id])
    @follower.user_id = params[:user_id]
    @follower.following_id = params[:following_id]
    @follower.favorite = params[:favorite]

    if @follower.save
      redirect_to followers_url, notice: "Follower updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @follower = Follower.find_by(user_id: current_user.id, following_id: params[:id])
    @follower.destroy

    redirect_to users_url, notice: "You are not following #{User.find_by(id: params[:id]).full_name} anymore"
  end
end

app/views/followers/edit.html.erb
<div class="page-header">
  <h1>Editing Follower #<%= @follower.id %></h1>
</div>

<%= form_tag(follower_url(@follower), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :user_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= number_field_tag :user_id, @follower.user_id, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :following_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= number_field_tag :following_id, @follower.following_id, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :favorite, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= check_box_tag :favorite, 1, @follower.favorite? %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update Follower", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/followers/index.html.erb
<div class="page-header">
  <h1>Followers</h1>
</div>

<p><%= link_to 'Add a New Follower', new_follower_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>User</th>
      <th>Following</th>
      <th>Favorite</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @followers.each do |follower| %>
      <tr>
        <td><%= follower.following.full_name %></td>
        <td><%= follower.followed.full_name %></td>
        <td><%= follower.favorite? %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, follower_url(follower), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_follower_url(follower), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, follower_url(follower), method: 'delete', data: { confirm: "Do you really want to delete this follower?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/followers/new.html.erb
<div class="page-header">
  <h1>New Follower</h1>
</div>

<%= form_tag(followers_url, method: 'post', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :user_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :user_id, options_from_collection_for_select(@users, "id", "full_name"), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :following_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :following_id, options_from_collection_for_select(@users, "id", "full_name"), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :favorite, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= check_box_tag :favorite %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Follower", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/followers/show.html.erb
<div class="page-header">
  <h1>Follower #<%= @follower.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt>User</dt>
  <dd><%= @follower.user_id %></dd>

  <dt>Following</dt>
  <dd><%= @follower.following_id %></dd>

  <dt>Favorite</dt>
  <dd><%= @follower.favorite? %></dd>

</dl>