config/routes.rb
Talkyapp::Application.routes.draw do
  devise_for :users
  root to: 'users#index'

  get '/genres/new', controller: 'genres', action: 'new', as: 'new_genre'
  post '/genres', controller: 'genres', action: 'create', as: 'genres'

  get '/genres', controller: 'genres', action: 'index'
  get '/genres/:id', controller: 'genres', action: 'show', as: 'genre'

  get '/genres/:id/edit', controller: 'genres', action: 'edit', as: 'edit_genre'
  patch '/genres/:id', controller: 'genres', action: 'update'

  delete '/genres/:id', controller: 'genres', action: 'destroy'

  get '/categories/new', controller: 'categories', action: 'new', as: 'new_category'
  post '/categories', controller: 'categories', action: 'create', as: 'categories'

  get '/categories', controller: 'categories', action: 'index'
  get '/categories/:id', controller: 'categories', action: 'show', as: 'category'

  get '/categories/:id/edit', controller: 'categories', action: 'edit', as: 'edit_category'
  patch '/categories/:id', controller: 'categories', action: 'update'

  delete '/categories/:id', controller: 'categories', action: 'destroy'

  get '/followers/new', controller: 'followers', action: 'new', as: 'new_follower'
  post '/followers', controller: 'followers', action: 'create', as: 'followers'

  get '/followers', controller: 'followers', action: 'index'
  get '/followers/:id', controller: 'followers', action: 'show', as: 'follower'

  get '/followers/:id/edit', controller: 'followers', action: 'edit', as: 'edit_follower'
  patch '/followers/:id', controller: 'followers', action: 'update'

  delete '/followers/:id', controller: 'followers', action: 'destroy'

  get '/stories/new', controller: 'stories', action: 'new', as: 'new_story'
  post '/stories', controller: 'stories', action: 'create', as: 'stories'

  get '/stories', controller: 'stories', action: 'index'
  get '/stories/:id', controller: 'stories', action: 'show', as: 'story'

  get '/stories/:id/edit', controller: 'stories', action: 'edit', as: 'edit_story'
  patch '/stories/:id', controller: 'stories', action: 'update'

  delete '/stories/:id', controller: 'stories', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create', as: 'users'

  get '/users', controller: 'users', action: 'index'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/models/category.rb
class Category < ActiveRecord::Base

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :go_to_home

  def go_to_home
    redirect_to root_url, :alert => "This page does not exist."
  end

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by(id: params[:id])
  end

  def new
  end

  def create
    @category = Category.new
    @category.name = params[:name]
    @category.description = params[:description]

    if @category.save
      redirect_to categories_url, notice: "Category created successfully."
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find_by(id: params[:id])
  end

  def update
    @category = Category.find_by(id: params[:id])
    @category.name = params[:name]
    @category.description = params[:description]

    if @category.save
      redirect_to categories_url, notice: "Category updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find_by(id: params[:id])
    @category.destroy

    redirect_to categories_url, notice: "Category deleted."
  end
end

app/views/categories/edit.html.erb
<div class="page-header">
  <h1>Editing Category #<%= @category.id %></h1>
</div>

<%= form_tag(category_url(@category), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :name, @category.name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :description, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :description, @category.description, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update Category", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/categories/index.html.erb
<div class="page-header">
  <h1>Categories</h1>
</div>

<p><%= link_to 'Add a New Category', new_category_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, category_url(category), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_category_url(category), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, category_url(category), method: 'delete', data: { confirm: "Do you really want to delete this category?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<div class="page-header">
  <h1>New Category</h1>
</div>

<%= form_tag(categories_url, method: 'post', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :name, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :description, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :description, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Category", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/categories/show.html.erb
<div class="page-header">
  <h1>Category #<%= @category.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt>Name</dt>
  <dd><%= @category.name %></dd>

  <dt>Description</dt>
  <dd><%= @category.description %></dd>

</dl>