config/routes.rb
Talkyapp::Application.routes.draw do
  devise_for :users
  root to: 'users#index'

  get '/genres/new', controller: 'genres', action: 'new', as: 'new_genre'
  post '/genres', controller: 'genres', action: 'create', as: 'genres'

  get '/genres', controller: 'genres', action: 'index'
  get '/genres/:id', controller: 'genres', action: 'show', as: 'genre'

  get '/genres/:id/edit', controller: 'genres', action: 'edit', as: 'edit_genre'
  patch '/genres/:id', controller: 'genres', action: 'update'

  delete '/genres/:id', controller: 'genres', action: 'destroy'

  get '/categories/new', controller: 'categories', action: 'new', as: 'new_category'
  post '/categories', controller: 'categories', action: 'create', as: 'categories'

  get '/categories', controller: 'categories', action: 'index'
  get '/categories/:id', controller: 'categories', action: 'show', as: 'category'

  get '/categories/:id/edit', controller: 'categories', action: 'edit', as: 'edit_category'
  patch '/categories/:id', controller: 'categories', action: 'update'

  delete '/categories/:id', controller: 'categories', action: 'destroy'

  get '/followers/new', controller: 'followers', action: 'new', as: 'new_follower'
  post '/followers', controller: 'followers', action: 'create', as: 'followers'

  get '/followers', controller: 'followers', action: 'index'
  get '/followers/:id', controller: 'followers', action: 'show', as: 'follower'

  get '/followers/:id/edit', controller: 'followers', action: 'edit', as: 'edit_follower'
  patch '/followers/:id', controller: 'followers', action: 'update'

  delete '/followers/:id', controller: 'followers', action: 'destroy'

  get '/stories/new', controller: 'stories', action: 'new', as: 'new_story'
  post '/stories', controller: 'stories', action: 'create', as: 'stories'

  get '/stories', controller: 'stories', action: 'index'
  get '/stories/:id', controller: 'stories', action: 'show', as: 'story'

  get '/stories/:id/edit', controller: 'stories', action: 'edit', as: 'edit_story'
  patch '/stories/:id', controller: 'stories', action: 'update'

  delete '/stories/:id', controller: 'stories', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create', as: 'users'

  get '/users', controller: 'users', action: 'index'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Talkyapp</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.0.2/cosmo/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 60px;
    }
  </style>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" ></script>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
  <meta charset="utf-8">
  <style>
      #map-canvas {
        margin: 0;
        padding: 0;
        height: 100%;
      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
    <script>
function initialize() {
  var myLatlng = new google.maps.LatLng(<%= @latitude %>, <%= @longitude %>);
  var mapOptions = {
    zoom: 15,
    center: myLatlng,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);

  var marker = new google.maps.Marker({
      position: myLatlng,
      map: map,
      title: 'This is your address location'
  });

}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>

</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if user_signed_in? %>
        <%= link_to Rails.application.class.parent_name, user_url(current_user.id), :class => "navbar-brand" %>
      <% else %>
        <%= link_to Rails.application.class.parent_name, user_url("sign_in"), :class => "navbar-brand" %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Create New Story", new_story_url %></li>
        <li><%= link_to "See All Users", users_url %></li>
        <li><%= link_to "See All Stories", stories_url(cat: "all") %></li>
        <% if user_signed_in? %>
        <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
        <li><%= link_to("Update Profile (@#{current_user.username})", edit_user_url(current_user))  %></li>
        <% else %>
        <li><%= link_to('Login', new_user_session_path)  %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-dismissable alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>